import { metres, metresPerSec, metresPerSec2, perMetre, perRadian, perSecond, radians, radiansPerSec, seconds } from './units';

export const CONSTANTS = Object.freeze({
  NUMERICS: Object.freeze({
    SERIES_TERMS: 24,
  }),
  TIME: Object.freeze({
    SIM_DT: seconds(1 / 120),
    MAX_FRAME_TIME: seconds(0.25),
  }),
  RNG: Object.freeze({
    DEFAULT_SEED: 1,
    MULTIPLIER: 1664525,
    INCREMENT: 1013904223,
    MODULUS: 4294967296,
  }),
  WATER: Object.freeze({
    WATER_GRAVITY: metresPerSec2(-1.2),
    WATER_DRAG_QUADRATIC: perMetre(0.003),
    WATER_THRUST: metresPerSec2(32),
    WATER_TURN_RATE: radiansPerSec(4.8),
    WATER_REDIRECT_RATE: perSecond(12),
    WATER_STEER_LEAD: radians(0.45),
    WATER_FLOW_MIN_SPEED: metresPerSec(1),
    WATER_MAX_THRUST_SPEED: metresPerSec(26),
    TURN_COST: perRadian(0.01),
    AIR_GRAVITY: metresPerSec2(-18),
  }),
  ENTRY: Object.freeze({
    PERFECT_ANGLE: radians(0.09),
    CLEAN_ANGLE: radians(0.26),
    SLOPPY_ANGLE: radians(0.7),
    CLEAN_RETENTION: 0.97,
    SLOPPY_RETENTION: 0.72,
    FLOP_RETENTION: 0.45,
    PERFECT_BONUS: metresPerSec(2.25),
    PERFECT_STREAK_BONUS: metresPerSec(0.4),
    PERFECT_BONUS_CAP: metresPerSec(5.5),
    CLEAN_BONUS: metresPerSec(1),
    FLOP_LOCKOUT: seconds(0.25),
    SKIP_THRESHOLD: metresPerSec(4),
    SKIP_MIN_SPEED: metresPerSec(8),
    SKIP_SETTLE_SPEED: metresPerSec(0.25),
    SKIP_RESTITUTION: 0.6,
  }),
  SURFACE: Object.freeze({
    SURFACE_Y: metres(0),
    HYSTERESIS: metres(0.15),
    ROOT_EPSILON: seconds(1e-12),
    ANGLE_EPSILON: radians(1e-12),
    MAX_CROSSINGS_PER_STEP: 8,
  }),
  PLAYER: Object.freeze({
    START_DEPTH: metres(-4),
    START_SPEED_X: metresPerSec(12),
    START_SPEED_Y: metresPerSec(-2),
    DOLPHIN_LENGTH: metres(2.5),
  }),
  CAMERA: Object.freeze({
    RESPONSE: perSecond(5),
    LOOK_AHEAD: seconds(0.3),
    VISIBLE_HEIGHT: metres(50),
  }),
  TUNING_RANGES: Object.freeze({
    WATER_GRAVITY: Object.freeze({ MIN: -8, MAX: 0, STEP: 0.1 }),
    WATER_DRAG_QUADRATIC: Object.freeze({ MIN: 0, MAX: 0.03, STEP: 0.001 }),
    WATER_THRUST: Object.freeze({ MIN: 0, MAX: 80, STEP: 1 }),
    WATER_MAX_THRUST_SPEED: Object.freeze({ MIN: 8, MAX: 60, STEP: 1 }),
    WATER_TURN_RATE: Object.freeze({ MIN: 0.5, MAX: 12, STEP: 0.1 }),
    WATER_REDIRECT_RATE: Object.freeze({ MIN: 1, MAX: 30, STEP: 0.5 }),
    WATER_STEER_LEAD: Object.freeze({ MIN: 0.05, MAX: 1.2, STEP: 0.01 }),
    TURN_COST: Object.freeze({ MIN: 0, MAX: 0.15, STEP: 0.005 }),
    AIR_GRAVITY: Object.freeze({ MIN: -36, MAX: -2, STEP: 0.5 }),
    PERFECT_BONUS: Object.freeze({ MIN: 0, MAX: 8, STEP: 0.25 }),
    PERFECT_STREAK_BONUS: Object.freeze({ MIN: 0, MAX: 2, STEP: 0.1 }),
    PERFECT_BONUS_CAP: Object.freeze({ MIN: 0, MAX: 16, STEP: 0.5 }),
    CLEAN_BONUS: Object.freeze({ MIN: 0, MAX: 5, STEP: 0.25 }),
    RETENTION: Object.freeze({ MIN: 0, MAX: 1, STEP: 0.01 }),
    FLOP_LOCKOUT: Object.freeze({ MIN: 0, MAX: 1, STEP: 0.05 }),
  }),
});
